### ISSUE TITLE
Intermittent remote cursor 

### ISSUE THREAD

**Issue by user8446** [gujjwal00/avnc#49] opened 2022-01-21 20:11 UTC
Hello,

I have noticed that the remote cursor disappears and reappears randomly when using the client. If the mouse is moved on the remote machine, the cursor appears all the time as normal. 

However, even though the remote cursor disappears, the touch points are still correct and I can see on the remote machine monitor that it is actually moving correctly.

I have tried enabling mouse keys and I'm on the local LAN so bandwidth wouldn't be an issue which didn't make a difference.

TightVNC server 2.8.63 for Windows
Windows 10

Thank you

**Comment by gujjwal00** [comment] 2022-01-22 02:23
Thanks @user8446.
I can reproduce the issue. Will look into it.

**Comment by gujjwal00** [comment] 2022-01-22 11:42
Hi @user8446 , this looks like an issue with TigerVNC.

I tried MultiVNC & androidVNC (10+ year old), and the issue can be reproduced with both of them. I also tried bVNC but it exhibits the issue slightly differently: sometimes pointer is completely invisible until moved on the remote machine, and sometimes it hides after some use (happened couple of times).

Can you please check if any other app works correctly?

**Comment by user8446** [comment] 2022-01-22 18:12
I am actually using [TightVNC](https://www.tightvnc.com/), not TigerVNC.

I could not reproduce the issue with [MutiVNC](https://f-droid.org/en/packages/com.coboltforge.dontmind.multivnc/). It would sometimes disappear only while moving but that's not a problem because of the purple highlight circle showing and then take a second for it to reappear but it always reappeared.

**Comment by gujjwal00** [comment] 2022-01-22 18:33
> I am actually using TightVNC, not TigerVNC.

Sorry, mistyped. I was referring  to TightVNC too.

> I could not reproduce the issue with MutiVNC. It would sometimes disappear only while moving but that's not a problem because of the purple highlight circle showing and then take a second for it to reappear but it always reappeared.

I can reliably reproduce it with MultiVNC. For me it is more frequent when cursor is moved quickly and you are on Desktop (i.e. no app is open).

**Comment by user8446** [comment] 2022-01-22 18:46
Hi, I just tried bVNC and couldn't recreate on that app as well.

To eliminate a settings issue, I have "Hide remote pointer" off in the app server settings and "Hide local (Android) pointer" off in Settings > Input

With those settings, I should at least have a full time local pointer which would be a workaround but it never appears (Moto g7 / Android 10)

Anything else to try to debug?

**Comment by gujjwal00** [comment] 2022-01-22 19:04
Thanks, I am using the same settings. I will try to pinpoint the issue tomorrow.

If you can, please try:
- androidVNC from F-Droid
- a different VNC server, maybe UltraVNC?

**Comment by user8446** [comment] 2022-01-22 19:37
I did try androidVNC and I could recreate the issue. The only difference is the local android cursor was always visible.

**Comment by gujjwal00** [comment] 2022-01-23 14:21
I did some testing, and its definitely an issue with TightVNC.

**Reproduction:**
Best way I found to trigger this is to *quickly* move the cursor on remote server. Try to 'fling' the cursor, like you fling a list on Android. If you move it fast enough, the cursor should disappear. You don't have to do anything from the client to trigger this.

Cursor will stay disappeared until something changes on screen, e.g. a clock updates or new window opens.

This issue is more apparent in AVNC & androidVNC beause both use direct touch by default. So cursor position is changed very quickly. If you disable direct touch in AVNC settings, it should behave similar to MultiVNC.

**bVNC:**
By default, bVNC draws the cursor locally in client. It only receives cursor position events from the server. That's why it does not show this issue. bVNC does not have a way to override this behavior from UI, but if you disable local cursor support in code to force cursor rendering on server, it will show the same issue. It you want to test this, you can try the following APK: [bVNC-app-debug-arm64.zip](https://github.com/gujjwal00/avnc/files/7920633/bVNC-app-debug-arm64.zip)

> I did try androidVNC client and I could recreate the issue. The only difference is the local android cursor was always visible.

Local Android cursor should be visible in AVNC when using a Mouse. If it is not, then its a bug. Please double-check that `Hide local (Android) pointer` setting is off.

**Comment by user8446** [comment] 2022-01-23 17:12
I went ahead and switched to UltraVNC server permanently which eliminates the issue. 

Just for future info, I did find https://github.com/novnc/noVNC/issues/1419 which describes the same issue. In the `[link](https://github.com/novnc/noVNC/blob/master/core/rfb.js#L183)` in that post, the code comment describes how TightVNC handles the cursor.

Thank you for helping research!

**Comment by gujjwal00** [comment] 2022-01-30 13:03
I have found a really nice way to support client-side cursor rendering (using [glTexSubImage2D](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexSubImage2D.xml)). It should improve cursor responsiveness, and as a side benefit, would workaround the bug in TightVNC. I will keep this issue open until then.

**Comment by user8446** [comment] 2022-01-30 19:04
Nice!

**Comment by gujjwal00** [comment] 2022-03-26 18:35
It turned out slightly more complex than I thought, but client-side cursor rendering is now supported. It unlocked many other features and comes with pretty big improvements to cursor responsiveness. There is essentially zero lag to cursor movement now.

- Issue with TightVNC is now fixed (as a workaround)
- Frame will now follow the cursor
- There is a new input preference for 'Swipe sensitivity'

@user8446 can you please try it? CI built APK: https://github.com/gujjwal00/avnc/suites/5812767723/artifacts/194574168

**Comment by user8446** [comment] 2022-03-26 19:35
I just tried and it and appreciate the new swipe sensitivity setting and I do notice the improved cursor responsiveness. Nice! 

I'm on UltraVNC server now so I'll have to try TightVNC when I have access to that machine.

**Comment by user8446** [comment] 2022-03-29 17:14
Update: I just tried TightVNC server and everything works as expected. I have also been using this AVNC beta client now for the last few days with no issues.

**Comment by gujjwal00** [comment] 2022-04-02 08:25
AVNC v1.8.0 is now available on F-Droid.

**Closed by gujjwal00** 2022-04-02 08:25 UTC
