### ISSUE TITLE
[enhancement] panning should respect zoom level

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gujjwal00/avnc#66] opened 2022-03-09 18:27 UTC
Hi,

When using your app, I sometimes have to click the cross at the top right corner of the remote app window to close it.

I sat minimum zoom to 70% and was under the impression that the best way to close an app with my fat fingers would be to zoom in, then pan to the corner until the corner of the window is roughly in the middle of the screen, making it easier to reach.

But with the current implementation, panning does not allow to go "over the edge" of the window, making this strategy useless.

The end result is that I *think* that expected behavior of minimum zoom would allow to pan over the edge, to make sure that edge of screen remote event are not on the edge of the screen of the android phone, making them easier to click on.

I'll let you decide if you think this deserves a change.

Thanks for reading!

**Comment by gujjwal00** [comment] 2022-03-10 03:34
Min/Max zoom controls *how much* you can zoom in/out (e.g. I always set minimum zoom to 100% because I usually don't need smaller frame). It doesn't affect the usable area of the screen.

I would suggest you to try disabling **Direct Touch**, and use 1 finger swipe for precise control.

**Comment by thiswillbeyourgithub** [comment] 2022-03-10 17:05
I think I don't see any use case where it would be useful to zoom out in that case. However, Direct touch is a must have for my use case.

Thanks for the answer.

**Comment by gujjwal00** [comment] 2022-03-11 16:27
> I think I don't see any use case where it would be useful to zoom out in that case.

Yeah, I don't use zoom less then 100%  either. I originally added it because other clients I used had this feature, and since then I have seen some users use this feature when their device is in portrait orientation.

So, can I close this issue?

**Comment by thiswillbeyourgithub** [comment] 2022-03-12 10:22
> So, can I close this issue?

Your call! I stil think this feature would be useful and desirable to a lot of people and that it is not expected behavior.

But your app is already awesome and well polished, plus I made way too many issues recently and I certainly don't want to make this app feel like a burden to you :)

Your call, thank you already.

**Comment by gujjwal00** [comment] 2022-04-11 17:19
Well, there is no technical problem with increasing minimum zoom. For AVNC, its just a number, only used to coerce the current zoom. Main issue is how to implement the preference UI.

Right now, minimum is always less than or equal to maximum. I don't want to have a UI where minimum can go above maximum. I believe that would be confusing from users' perspective. We will have to probably link both of them together so maximum always remains larger than minimum.  
 
As for the real issue here, I have been playing with a 'Free-flow' mode, where frame is not constrained to align with screen edges. You can move the frame anywhere, in any direction. But I have not figured out all details yet.

**Comment by user8446** [comment] 2022-04-11 17:59
I agree, maximum would have to at least be equal to the minimum automatically. Not a bug or big deal, just a small extra step after connecting.

**Closed** 2023-03-28 07:43 UTC
