### ISSUE TITLE
Suggestion: TV Remote Gesture Style

### ISSUE THREAD

**Issue by mohammedthejihadist** [gujjwal00/avnc#222] opened 2024-03-22 11:04 UTC
I don't know if the VNC protocol allows this, but I think TV gesture style with volume buttons would be very useful. 

Basically it would just be touchpad style except:
- two volume buttons or volume slider on top of screen
- keyboard pops up when connected
- preset: clipboard sync disabled
- preset: double tap and swipe: scroll remote content

**Comment by mohammedthejihadist** [comment] 2024-03-22 22:08
I feel dumb for not trying to use the phones volume buttons, thank you for letting me know! 154 looks great

**Comment by gujjwal00** [comment] 2024-03-24 06:16
No problem. I am closing this as duplicate of #154 .

**Closed** 2024-03-24 06:16 UTC
