### ISSUE TITLE
Long press doesn't work correctly as right click 

### ISSUE THREAD

**Issue by AnatolyHB** [gujjwal00/avnc#113] opened 2022-12-25 12:26 UTC
Hello. Thank you a lot for your great ap! 
I have some problem, I have set up "Long press" - for a "Right-click". But when I select text or some items and use long touch it works like left-click mouse then right click mouse (first it deselects items or text, then open context menu only for one item/word).
This problem appears only if "Drag" config as "Drag remote content". My device is Redmi note 8 pro.
I cold set up "Right-click" for "Two finger tap", but it's not useful to open keyboard from tolbar. Maybe it has sense to add an option "Open keyboard" for "Long press".

- App Version: 2.0.2 (17)
- Android Version: 11 (30)

**Comment by gujjwal00** [comment] 2022-12-25 12:51
Hi @AnatolyHB, thanks for your report. This has already been fixed via https://github.com/gujjwal00/avnc/commit/6189f4a74164f23aaf5385082819106b288407d4. It was a regression in v2.0.2, caused by https://github.com/gujjwal00/avnc/commit/1a1815cdb528de32080771729ad35b10cb8a1b1a which refactored gesture handling and added support for double-tap-swipe detection (not exposed in UI yet) (re #94).

I will create a new release later today.

**Comment by AnatolyHB** [comment] 2022-12-25 13:13
Great! Thank you for the quick answer.

**Comment by AnatolyHB** [comment] 2022-12-25 19:19
Thanks. Now it works perfectly!

**Closed** 2022-12-25 19:19 UTC
