### ISSUE TITLE
VNC URI scheme not supported?

### ISSUE THREAD

**Issue by Android-X13** [gujjwal00/avnc#68] opened 2022-03-11 23:30 UTC
Hi, based on what I've read in [RFC 7869](https://datatracker.ietf.org/doc/html/rfc7869) I thought I could run something like this (via activity manager), but the app doesn't recognize the connection name and instead displays a login window:

`am start -d vnc://host:port?ConnectionName=name`

Supplying the username and password also doesn't work as it still asks for login information:

`am start -d vnc://host:port?VncUsername=user&VncPassword=pass`

`am start -d vnc://host:port?ConnectionName=name&VncUsername=user&VncPassword=pass`

Is the VNC URI scheme not supported? Ideally I'd like to just use the name of the connection that is already stored and the rest to be handled by the app. Can it be done?

By the way, it would be a useful feature if you allowed to create connection shortcuts on the homescreen like some SSH clients do (one example would be the app called Termius).

**Comment by gujjwal00** [comment] 2022-03-12 01:15
VNC URIs are supported, so it might be a bug. Let me check.

**Comment by gujjwal00** [comment] 2022-03-12 17:18
So the issue here is not with AVNC, but with shell processing. As you probably already know, `&` is a special character used for combining commands.  So `am start -d vnc://host:port?VncUsername=user&VncPassword=pass` is processed by shell as `am start -d vnc://host:port?VncUsername=user` and `VncPassword=pass`  separately. And because password is missing,  AVNC prompts for credentials. You can run `echo $VncPassword` afterwords to confirm that a shell variable is created by second command.

Using quotes around URI should work: `am start -d 'vnc://host:port?VncUsername=user&VncPassword=pass'`

>am start -d vnc://host:port?ConnectionName=name

> Ideally I'd like to just use the name of the connection that is already stored and the rest to be handled by the app

AVNC does not support this yet! For one, AVNC doesn't enforce unique connection names. Second, I was not sure if anybody will use this feature so I didn't spend any time implementing it. So If this is something you need frequently, we can work something out, but IMO, shell history reduces the the burden of typing the URI repeatedly. 

> By the way, it would be a useful feature if you allowed to create connection shortcuts on the homescreen like some SSH clients do (one example would be the app called Termius).

Thanks, I will look into it, but I can't promise any timeline.

**Comment by Android-X13** [comment] 2022-03-12 19:43
You are of course right about the `&` character and the reason it wasn't working. I felt like a noob for a moment after reading your post. :grin:

After some testing I now see that parameters like `ChannelType`, `SshUsername`, `SshPassword`, etc, are also supported by your app in the provided VNC URI which is great.

The reason I wanted to use `ConnectionName` is because I didn't want to hardcode the credentials inside my script, since they're already stored in the app's config. Now I have to hardcode both the VNC and SSH credentials (I don't see in the RFC any way to use an SSH private key with the URI). The script is a Termux "task" which is added in my homescreen. When tapping on it, it checks if it's in my home network in which case it calls AVNC with the local IP of the destination, otherwise it assumes it needs to connect through the Internet and uses the target's public IP as a host. Anyway at least the URIs are working now so it's not that big of a deal.

I just noticed something really weird though. Instead of running `am start -d 'URI'` I also tried to use an Intent URI:

`am start 'intent://host:port?VncUsername=user&VncPassword=pass#Intent;scheme=vnc;package=com.gaurav.avnc;end'`

Which works. If I give a wrong host or port, it won't connect.. but if I give wrong `VncUsername` and/or `VncPassword` it connects (!!) normally. It seems that AVNC somehow remembers the connection? I even removed the stored connection from inside the app and deleted the cache, but this is still happening. However if I type in the intent URI the correct host and port, but without `VncUsername`and `VncPassword`, it doesn't connect (as expected) and displays the login screen:

`am start 'intent://host:port#Intent;scheme=vnc;package=com.gaurav.avnc;end'`

**Comment by gujjwal00** [comment] 2022-03-14 18:25
> You are of course right about the & character and the reason it wasn't working. I felt like a noob for a moment after reading your post.

I didn't notice it immediately either. When I attached the debugger only partial URI was passed to AVNC and that's when it clicked.

> The reason I wanted to use ConnectionName is because I didn't want to hardcode the credentials inside my script, since they're already stored in the app's config. Now I have to hardcode both the VNC and SSH credentials (I don't see in the RFC any way to use an SSH private key with the URI). The script is a Termux "task" which is added in my homescreen. When tapping on it, it checks if it's in my home network in which case it calls AVNC with the local IP of the destination, otherwise it assumes it needs to connect through the Internet and uses the target's public IP as a host. Anyway at least the URIs are working now so it's not that big of a deal.

I will try to implement it. Just have to figure out how it may interact with #51 in future. 

>Which works. If I give a wrong host or port, it won't connect.. but if I give wrong VncUsername and/or VncPassword it connects (!!) normally. It seems that AVNC somehow remembers the connection? I even removed the stored connection from inside the app and deleted the cache, but this is still happening.

I cannot reproduce this. Changing password correctly results in 'Authentication failed' for me. AVNC doesn't do any caching of VNC URI.

**Comment by Android-X13** [comment] 2022-03-14 18:54
That's really strange, I can still reproduce it right now:

`am start 'intent://host:port?VncUsername=wrong_user&VncPassword=wrong_pass#Intent;scheme=vnc;package=com.gaurav.avnc;end'`

It opens AVNC and immediately connects to the given `host:port` without even prompting for the correct credentials!

Maybe to reproduce it on your side:

1. Connect once via `am start -d 'vnc://host:port?VncUsername=CORRECT_USER&VncPassword=CORRECT_PASS'`

2. Disconnect and connect via 
`am start 'intent://host:port?VncUsername=CORRECT_USER&VncPassword=CORRECT_PASS#Intent;scheme=vnc;package=com.gaurav.avnc;end'`

3. Disconnect and try to connect via
`am start 'intent://host:port?VncUsername=WRONG_USER&VncPassword=WRONG_PASS#Intent;scheme=vnc;package=com.gaurav.avnc;end'`

At least these were my steps IIRC.

Anyway thank you for your time and your responses. URIs are working, all good.

**Comment by gujjwal00** [comment] 2022-03-15 23:21
Unfortunately I am still unable to reproduce it. Anyway, I am closing this issue. I will investigate the caching behavior when I have some time.

**Closed by gujjwal00** 2022-03-15 23:21 UTC

**Comment by sudomain** [comment] 2023-01-15 15:56
Hi I'm also looking to make a similar script that programmatically opens AVNC. The `ConnectionName` parameter that's briefly mentioned here would allow me to store credentials only in AVNC and not hardcoded in a script. Can this issue please be reopened for this parameter?

Alternatively, did @Android-X13 find a workaround to storing credentials in such a script?

**Comment by Android-X13** [comment] 2023-01-15 17:20
@sudomain Unfortunately there's no workaround (that I know of) to hardcoding the credentials in a script, other than having the app itself handle the `ConnectionName` parameter when feeded with the appropriate URI.

**Comment by gujjwal00** [comment] 2023-01-16 05:02
`ConnectionName` is now supported (https://github.com/gujjwal00/avnc/commit/9f8e13813bf7a6a40fb8d5f17c8f681edae1a2cb).
You should now be able to do something like this: `am start -d 'vnc://?ConnectionName=home'`

Note: Connection name is case sensitive.

**Comment by sudomain** [comment] 2023-01-16 13:57
Thank you!
