### ISSUE TITLE
Fullscreen on Samsung DeX

### ISSUE THREAD

**Issue by davidalben** [gujjwal00/avnc#23] opened 2021-12-03 17:14 UTC
Finally I've found a VNC client with PT_BR keyboard full support! Thank you!

I'm using Samsung DeX and avnc doesn't enter in fullscreen mode (which is selected in configs). There's always a top bar with minimize and close buttons and the apps bar on screen bottom.

I think what I want it is called "immersive mode" in Android. So this app would be perfect to use with Andronix in PT_BR.

**Comment by gujjwal00** [comment] 2021-12-04 09:21
Yeah, currently AVNC doesn't implement full Immersive mode Some reasons for this:
- It really messes with our layout handling, especially opening/closing of the soft keyboard.
- It interferes with Toolbar drawer because both of them use the "swipe-in from edge" to open.  
- I absolutely hate that part of the Android API. Android clears Immersive Mode flags on every chance it gets, AND their implementation differs across different Android versions.

I have a local branch which implements basic immersive mode but it has still some rough edges. So I will probably make it available as an experimental feature.

**Comment by davidalben** [comment] 2021-12-05 12:32
Thank you, @gujjwal00.
I think it should be great having immersive mode as an experimental feature. I understand what you say about "swap-in from edge" conflict, but I prefer to have a complete full-screen experience and fight with DeX bottom bar (this is what I do all time when I use other remote desktop solutions).
Please, let we know if you implement this.
Thanks, again!

**Comment by gujjwal00** [comment] 2021-12-06 10:52
Implemented in https://github.com/gujjwal00/avnc/commit/ca3e6c8b0445cef65779ff8127c345b8610a1a16.

You can use [this APK](https://github.com/gujjwal00/avnc/suites/4564571972/artifacts/122691993) to test it (you have to be logged-in to download the APK).

Enable `Settings => Experimental => Full immersive mode` to use this.

**Comment by davidalben** [comment] 2021-12-06 11:59
I've downloaded and unzipped the APK. Android installer warns me about "unknown developer", I click on "Install anyway" and it is forever "installing". Can't install this APK.

**Comment by gujjwal00** [comment] 2021-12-06 12:17
It installs correctly on my device.

You can try installing via 'adb', if you're familiar with it.
Or maybe compile it yourself?

**Comment by gujjwal00** [comment] 2021-12-06 16:13
Thanks for the video, @zequinh4 . I will look more into this tomorrow.

**Comment by davidalben** [comment] 2021-12-06 16:14
> You can try installing via 'adb', if you're familiar with it. Or maybe compile it yourself?
Sorry, I don't have a PC here to try this (only DeX).

**Comment by gujjwal00** [comment] 2021-12-07 06:39
I have tried the tablet mode in Android emulator, and AVNC is working correctly there. I couldn't find anything related via Google. 

It might be something specific to Samsung DeX. Are you using any open source app which works correctly, e.g. VLC or Firefox?

**Comment by gujjwal00** [comment] 2021-12-07 10:34
@zequinh4 can you try this APK too: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7667561/app-debug.zip)
Note: You will have to remove old debug APK.

It adds another fullscreen flag which might help.

**Comment by davidalben** [comment] 2021-12-07 11:20
Yes! APK installed and working as expected!

I've had to select FHD resolution in server setup (instead of dynamic resolution - which shows black bars at left and right in my screen). Accent keys working (it seems sometimes it fails - need to investigate when).

Thank you, @gujjwal00!

Let us know when you put this version in some marketplace (F-Droid?).

**Comment by zequinh4** [comment] 2021-12-07 11:29
Hi. Sorry I didn't answer earlier... in Brazil it was still night. This last apk sent by you worked perfectly. Thanks again so much for supporting our community! If you need anything just get in touch! Hugs and success! Here is a video demonstrating how it works.

https://user-images.githubusercontent.com/51301335/145021361-7b0481cb-6109-4e6d-bca5-417f99f4f61f.mp4

**Comment by gujjwal00** [comment] 2021-12-07 13:16
Nice!

> Let us know when you put this version in some marketplace (F-Droid?).

I will make a release in few days, so it will probably be available on F-Droid next week. I am hoping to include #24 in the next release. If you guys want, you can review that PR and leave any suggestions, because I don't know Portuguese.

 > Hi @gujjwal00. Sorry I didn't answer earlier... in Brazil it was still night. 

Don't worry about it :+1:.
 
> Thanks again so much for supporting our community! If you need anything just get in touch! Hugs and success! 

Thank-you for the kind words! Deeply appreciate it.

**Comment by zequinh4** [comment] 2021-12-07 14:03
Hi @gujjwal00. I found a bug that I believe didn't exist before. Double-clicking with the left mouse button gives an error in the application and it closes. Here's video demonstrating and log of the app.


https://user-images.githubusercontent.com/51301335/145042848-8cae35b8-0071-49c9-b3ae-3f1212e3edbb.mp4


https://user-images.githubusercontent.com/51301335/145042863-f95556ea-166e-44f7-a412-2b5ccc22cb20.mp4

Archive PDF log app

[log.pdf](https://github.com/gujjwal00/avnc/files/7668822/log.pdf)

**Comment by gujjwal00** [comment] 2021-12-07 14:22
Couple of questions:
- Does it happen only when you double-click on some text **or** always?
- Does your distro copies the text to clipboard on double click?

Also can you please use txt format for the logs next time? Its hard to to follow the PDF logs due to line breaks.

**Comment by zequinh4** [comment] 2021-12-07 15:01
@gujjwal00 I did some testing and it only happens when you double left-click with text that has accents. Unaccented text and other areas do not present the problem. Follow videos demonstrating and log in txt. Hugs

[text.txt](https://github.com/gujjwal00/avnc/files/7669251/text.txt)

https://user-images.githubusercontent.com/51301335/145053015-32fc46cc-7ba6-4fa9-983a-765339a6f6eb.mp4


https://user-images.githubusercontent.com/51301335/145053071-496d450c-a7b4-43f8-a3d1-f88e21221e42.mp4


https://user-images.githubusercontent.com/51301335/145053113-098e0f9c-25ac-4c49-9a2b-f7295a78c467.mp4

**Comment by zequinh4** [comment] 2021-12-07 15:05
I also noticed that the same problem occurs when doing the key combination "Ctrl left + A" to be able to select all the text.

**Comment by gujjwal00** [comment] 2021-12-07 15:10
Yeah, Its an encoding mismatch. Clipboard text from server is received in ISO 8859-1, but AVNC is trying to decode it as UTF-8.

I am working on a fix.

**Comment by zequinh4** [comment] 2021-12-07 15:12
@gujjwal00 Reinstalled version available on F-droid (before adding fullscreen support). There is no such problem in it. Follow video and log.

[previusversionlog.txt](https://github.com/gujjwal00/avnc/files/7669344/previusversionlog.txt)

https://user-images.githubusercontent.com/51301335/145055011-1bc8d1a4-bd3e-4aec-aeb1-df7e65107142.mp4

**Comment by zequinh4** [comment] 2021-12-07 15:13
> Yeah, Its an encoding mismatch. Clipboard text from server is received in ISO 8859-1, but AVNC is trying to decode it as UTF-8.
> 
> I am working on a fix.


Thanks again

**Comment by gujjwal00** [comment] 2021-12-07 15:17
> Reinstalled version available on F-droid (before adding fullscreen support). There is no such problem in it.

It also has the same problem, but in release mode JNI checks are disabled, so the app is not crashing.

**Comment by gujjwal00** [comment] 2021-12-09 16:24
@zequinh4 you can test this APK for double-click issue: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7686766/app-debug.zip).

**Comment by zequinh4** [comment] 2021-12-09 16:45
Hello my friend @gujjwal00 . It is working perfectly in immersive mode. Thanks again for your huge dedication to the project.. A question... my knowledge of Kotlin is limited, I couldn't find something in the code about the following question: is there any time limit between pressing one key on the keyboard and another?. I say this because I noticed that when typing using accents it is necessary to press the accent key (eg '˜) and wait a while to press the vowel key. If pressed too quickly the accent is ignored. I've tested this on two different systems (Linux and Windows) and it happens on both.

In the video below I demonstrate that the first 4 key combinations (´ + e) ​​made quickly was not accepted... and the last one made with pause was accepted with accentuation. It may seem like a silly thing, however, during fast typing it is bothersome as accent typing is missing.

https://user-images.githubusercontent.com/51301335/145439251-50d18f9d-d086-4c39-8701-28261e99abea.mp4

**Comment by gujjwal00** [comment] 2021-12-09 16:59
There is no such time limit in the code. I will try to reproduce the issue on my side.

Is is possible that you are pressing the vowel key while the accent key is still down?

**Comment by zequinh4** [comment] 2021-12-09 17:17
The normal behavior outside of AVNC and that if the vowel is pressed while the accent key is pressed is = (é). Or if held down for a while, the expected result is = (´´´´é). However, inside AVNC if I hold down the accent key and press the vowel the result is = "e", that is, without accent and if pressed longer (´´´´é). Here's a video demonstrating the difference in behavior.

Video outside AVNC (android system)

https://user-images.githubusercontent.com/51301335/145444251-231c27ea-8ed1-4a33-97dc-bd0857f3f14e.mp4

Video inside AVNC

https://user-images.githubusercontent.com/51301335/145444294-4496231a-a12b-43b9-8c7b-c9c6f944d22a.mp4

**Comment by gujjwal00** [comment] 2021-12-09 17:26
Yeah, AVNC waits for accent key release before starting the composition. See #14 for some background on this, and [docs](https://github.com/gujjwal00/avnc/blob/9c6856de16c42529d45a8d3bca3c8ed8272767c4/app/src/main/java/com/gaurav/avnc/ui/vnc/KeyHandler.kt#L272) for current algorithm.

**Comment by davidalben** [comment] 2021-12-09 18:04
@zequinh4, the normal use of accent keys is to press and release the accent key then press and release the vowel key. I've never held the accent while pressing the vowel. This behavior comes from typewriter machines (which I believe to be the unique here who used them, decades ago...).

Only today, after your comment, I realized that holding the accent key while pressing the vowel key also works.

**Comment by zequinh4** [comment] 2021-12-09 19:21
I think I expressed myself poorly. The problem is not pressing the keys together, but when pressed very closely together. When you have time do a quick typing test by your side please @gujjwal00 @davidalben

**Comment by zequinh4** [comment] 2021-12-09 21:18
@gujjwal00  I was analyzing their codes and noticed that the accent entry only takes effect if the key is pressed twice (eg ´ + ´ = ´) or after spacce (eg ´ + space key = ´) or after vowel (eg ´ + a = á). However, smoothing the natural behavior of accentuation in different operating systems, I notice that simply pressing the accent key already "prints" the character and then the join is done (eg just pressed ´ = ´). Associate this combination with any other letter that is joined (eg ´ + a = á). Likewise, if the association is made outside AVNC of characters that do not accept accents, it is printed and the letter as well (ex. ´ + d = ´d). This does not happen in AVNC which "prints" only the letter (eg inside AVNC ´ + d = d). However, seeing your code I'm not ideal of how to get around it. If you have not understood my explanation, please let me know. Once again, thank you very much for your dedication. Hugs my friend

**Comment by gujjwal00** [comment] 2021-12-10 16:42
I can reproduce the issue, but it will take some time to fix because the composition algorithm needs to be reworked.

> I notice that simply pressing the accent key already "prints" the character and then the join is done

Although It depends on the app/OS you are using, current behavior is consistent with Notepad in Windows & gedit in Ubuntu (which I test on). I have already tried sending accents immediately without waiting for next character, but VNC servers don't handle this correctly. That's why AVNC sends the final composed character.

**Comment by gujjwal00** [comment] 2021-12-11 08:18
APK with re-implemented composition algorithm: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7696661/app-debug.zip)
Hopefully this will solve both issues.

**Comment by zequinh4** [comment] 2021-12-11 09:45
Greetings @gujjwal00 . I did some quick typing and it seems to work perfectly. Thank you very much for your commitment and availability. Thank you so much. Good weekend my friend!

**Comment by gujjwal00** [comment] 2021-12-12 16:18
Tagged a new release: https://github.com/gujjwal00/avnc/commit/4e9a7b49c4c8dde862190899241d92e35f4b7d1d
It should be available on F-droid in couple of days.

**Closed by gujjwal00** 2021-12-12 16:18 UTC

**Comment by davidalben** [comment] 2021-12-12 20:47
Great news! Thank you very much, @gujjwal00!
