### ISSUE TITLE
need help connecting to my samsung TV Workspaces

### ISSUE THREAD

**Issue by MadMarksman42** [gujjwal00/avnc#257] opened 2024-10-03 08:22 UTC
the error the TV workspace displays is 
"Unable to connect to the remote PC becuse the encryption session was not create. Check if the encryped communication is supported in the remote PC's VNC program

Here's my wayvnc config file 
The TV needs to recognise the device as  a Mac for the vnc protocol; any suggestions

# /etc/wayvnc/wayvnc.conf

# General settings
address = 0.0.0.0                # Bind to all available interfaces, you can specify a specific IP if needed.
port = 5900                      # Default VNC port, change if necessary.
enable-auth =true                # Enable password protection (recommended).
username = jules
password = 826444
use_relative_paths=true
relax_encryption=true
certificate_file=tls_cert.pem
private_key_file_file=tls_key.pem
rsa_private_key_file=rsa_key.pem

**Comment by gujjwal00** [comment] 2024-10-03 09:58
Can you please test with the APK linked here: https://github.com/gujjwal00/avnc/issues/249#issuecomment-2368016828

**Comment by gujjwal00** [comment] 2024-10-13 10:55
Closing as duplicate of #249

**Closed by gujjwal00** 2024-10-13 10:55 UTC
