### ISSUE TITLE
Copy/Paste clipboard only works 1 way Linux to Android

### ISSUE THREAD

**Issue by seancrowe** [gujjwal00/avnc#62] opened 2022-03-04 03:23 UTC
On bVNC, I can copy and paste bidirectionally from client (Android 12) and host (Debian 10).

Om AVNC, I can copy only from host (Debian 10) to client (Android 12). Sometimes, rarely, it will work both ways for just an instant.

Setup:
Debian 10 running on proot on top of termux on Android 12 with tigervnc 1.9.0

Steps to reproduce
(I haven't tested outside of proot)

1. Install Termux from F-Droid
2. Install Debian 10 (or Ubuntu 20) using Andronix (or proot-distro, but I used Andronix)
3. Make sure you are using tigerVNC - Andronix will set this all up for you
4. Launch your VNC server 
5. Connect with bVNC and try copying and pasting between client and host - all works
6. Connect with AVNC and trying copying and pasting between client and host - only works from Linux to Android

This is my xstartup
```
#!/bin/bash
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
export PULSE_SERVER=127.0.0.1
touch $HOME/.Xauthority
export XAUTHORITY=$HOME/.Xauthority
vncconfig SendPrimary=0
echo $$ > /tmp/xsession.pid
. $HOME/.xsession
```

`vnconfig &` was ran and the proper settings are set.

What is super weird is that if I check a box in the VNC config window, the clipboard from Android will update the clipboard in Linux, but only once. Trying copy/paste again from Android to Linux and it wont work. If I check a box again in the VNC config window, the clipboard will update again from Android to Linux.

It is possible I am just stupid, and an extra step is needed for AVNC, and bVNC just does things differently.

**Comment by gujjwal00** [comment] 2022-03-04 12:28
Thanks for the detailed report @seancrowe.

Ideally, it should work both ways. But there were some changes in Android 12 related to clipboard access, and those might be the issue here. I did some limited testing only with an emulator.

I will take a closer look.

**Comment by gujjwal00** [comment] 2022-03-11 18:03
I can't find a real Android 12 device for now. But I tried again with emulator and copy-past works reliably in both directions.

Just to give more context, this is how clipboard access works in AVNC: 
- Host -> Client: When text is received from host, it is immediately placed on Android's clipboard.
- Client -> Host: Because AVNC will  be in background when you copy some text in some other app, It will check the clipboard when it comes to foreground (i.e. `onResume`). If text is found on clipboard, it will be sent to the server. On Android 12, you will sometimes see a toast `AVNC pasted from you clipboard` when AVNC comes to foreground.

Can you please test the following:
1. Copy some text on Android **before** connecting to server. Now connect and check if text is properly pasted on server.
2.  After connecting in AVNC, switch to another app (e.g. Messaging), copy something, and switch back to AVNC. Check the clipboard on server. Disconnect from server by pressing Back. Tap on top Address/URL bar in AVNC, and try to paste the text.

**Comment by gujjwal00** [comment] 2022-03-29 14:22
Any update @seancrowe?

**Comment by gujjwal00** [comment] 2022-04-02 08:32
Because I cannot reproduce the issue, and there is no progress here, I am closing this.

But, feel free to reopen if you want.

**Closed by gujjwal00** 2022-04-02 08:32 UTC

**Comment by gujjwal00** [comment] 2022-04-12 03:10
Yes, AVNC doesn't actively listen for clipboard changes.    If you are using multiple apps side-by, try tapping on AVNC after copying from other app. 


It is possible to register a clipboard listener, but I didn't want to read clipboard while in background due to privacy concerns.

**Comment by gujjwal00** [comment] 2023-01-15 05:24
This should be fixed now in https://github.com/gujjwal00/avnc/commit/71f84b594bf6269c52d37053a105e09c7ddb94ad
