### ISSUE TITLE
Stretched at 100% scale

### ISSUE THREAD

**Issue by Squaduck** [gujjwal00/avnc#177] opened 2023-06-15 17:24 UTC
At any quality level, the image appears stretched at 100% scale.
The image is at the correct size on the display, but appears horizontally stretched.

Some screenshots/captures of Yakuake (KDE Drop-Down terminal):

AVNC Screen Capture via ADB (AVNC's second highest quality preset):
![avnc_screencap](https://github.com/gujjwal00/avnc/assets/55469508/257533f6-457e-44cc-b440-d88e7f88672a)
Screenshot of what it should look like:
![ref_screenshot](https://github.com/gujjwal00/avnc/assets/55469508/f3968533-505e-43f0-8b14-12e7d21be563)
MultiVNC Screen Capture via ADB (doesn't appear stretched) (MultiVNC's default quality):
![MultiVNC_screencap](https://github.com/gujjwal00/avnc/assets/55469508/47b7e715-44f6-4736-a6c9-10708ec82f49)

The vnc server resolution is 1520x720, when my phone's usable resolution considering the camera cutout is 1523x720
my only theory is that because it's trying to center the 1520 width image on my 1523 width display, it is aligned between two pixels?
maybe it could be fixed by using nearest neighbor scaling at 100% resolution?
IDK.

I'm using the latest version of AVNC (2.2.3),
TigerVNC x0vncserver 1.13.1,
and Android 12

**Comment by gujjwal00** [comment] 2024-08-06 18:45
Hi @Squaduck really sorry for late response, but I am unable to reproduce this. I have tried a few different resolutions, and AVNC's image matches with MultiVNC for me.


> The vnc server resolution is 1520x720, when my phone's usable resolution considering the camera cutout is 1523x720
> my only theory is that because it's trying to center the 1520 width image on my 1523 width display, it is aligned between two pixels?

That should not be an issue. Centered image will just occupy the pixels staring from 1 till 1521. So one pixel will remain unused along left edge, while two pixels will remain unused along the right edge.

If you are still having this issue (or using AVNC at all 😀), do let me know.

**Comment by Squaduck** [comment] 2024-08-07 00:13
Hi, if I recreate the exact situation I still have the issue. However, I have no reason to be in that situation anymore because I'm no longer using TigerVNC (KRFB, the VNC server I swapped to, lets me be exact), and I am now fine with it being under my camera cutout anyway. (I'm unsure if that option wasn't available yet, or if I just didn't want to have stuff obscured.)
I never actually went back to MultiVNC, because AVNC just looks and feels so much better IMO. (Maybe MultiVNC has improved since then, but I haven't checked.)
Reference:
![Screenshot_20240806_193041](https://github.com/user-attachments/assets/ed98355a-aef5-4e55-bfaf-14b8e990e7c4)
Weird Size:
![Screenshot_20240806-191441_cropped](https://github.com/user-attachments/assets/758ff763-e56a-47bb-8b17-8bf6fcd9840b)
Proper Fullscreen (Exact cut-out fullscreen looks the same):
![Screenshot_20240806-193230_cropped](https://github.com/user-attachments/assets/dd17d101-78b0-4e51-9021-900cbbf4d195)

The phone I'm using is a Motorola Moto G Power (2022)
If you need any more information about my setup just let me know.
I'm willing to capture whatever debug info you might need.
I don't mind setting up a build environment either.

I'd understand if you don't bother fixing this issue since I'm the only person to ever have it, and I no longer actively have this issue.

Thanks for reaching out, and I hope you have a fantastic day :)

**Comment by gujjwal00** [comment] 2024-08-07 10:52
Thanks for the details, and yes, I would definitely like to fix this issue. I have created a test APK which prints a bunch of information on the screen.
APK: https://github.com/gujjwal00/avnc/actions/runs/10282730079/artifacts/1785108620

Please take two screenshots with this APK, one for stretched case & one for normal case.
Please capture the whole screen via adb. (e.g. `adb shell screencap -p  > avnc_normal.png`), and just attach the files here.

**Comment by Squaduck** [comment] 2024-08-07 22:16
![avnc_not_under_cutout_1520x720_case](https://github.com/user-attachments/assets/6cbf91a2-ed87-40c1-907b-b97576ad4dff)
![avnc_not_under_cutout_1523x720_case](https://github.com/user-attachments/assets/c0de0711-0304-4a91-8e3f-a52a149e30f9)
![avnc_not_under_cutout_1280x720_case](https://github.com/user-attachments/assets/75191b92-7505-4b6e-b7a9-dc172b08edc8)
Reference:
![avnc_reference_1280x720](https://github.com/user-attachments/assets/02edf16b-67c9-4f1c-93d2-27a10321259b)

**Comment by gujjwal00** [comment] 2024-08-08 03:08
Looks like you were right. Because renderer is using floating-point values to store frame position, it was not aligned to integral pixel boundary. I have added a fix. Please test the following APK to see if the problem is solved:
https://github.com/gujjwal00/avnc/actions/runs/10295171156/artifacts/1788569984

**Comment by Squaduck** [comment] 2024-08-08 20:38
![avnc_not_under_cutout_1280x720_case_after](https://github.com/user-attachments/assets/6751fbc0-3567-414f-949a-637228bcb005)
![avnc_not_under_cutout_1520x720_case_after](https://github.com/user-attachments/assets/890b42e0-13e3-446c-8b46-234db0cf3b56)
![avnc_not_under_cutout_1523x720_case_after](https://github.com/user-attachments/assets/52a21ddc-4ba6-441d-b9b8-8531762b4113)
![avnc_under_cutout_1600x720_case_after](https://github.com/user-attachments/assets/acfa6225-2e42-4579-938e-f7aac707271b)
Reference still applies.
Seems fixed to me!

**Comment by gujjwal00** [comment] 2024-08-09 11:24
Thanks a lot for the comprehensive testing. The fix will be included in next version.

**Closed by gujjwal00** 2024-08-09 11:24 UTC
