### ISSUE TITLE
Feature Request: setting default zoom level

### ISSUE THREAD

**Issue by PureIncompetence** [gujjwal00/avnc#77] opened 2022-05-06 17:38 UTC
Right now the default zoom-state on an opened connection in portrait mode seems to be determined by the width (a.k.a. the height in landscape mode) of the phone's screen, so it uses only ~ 50% of the phone's screen in portrait mode. Therefore everytime after connecting I need to zoom in at least until the height of the remote screen matches the height of the phone screen to be able to see something on the remote screen. (I'm gonna attach a screen record to show it.)

https://user-images.githubusercontent.com/66217283/167184119-d2911206-7eda-4afe-8cf2-d88ae18793de.mp4

In my opinion it'd make sense to either be able to set a default zoom level (which might need to be different in landscape mode than it would be in portrait mode) or - which would probably be easier and more convenient to most users - to automatically align the default zoom-level for portrait mode with the screen height of portrait mode.

**Comment by gujjwal00** [comment] 2022-07-18 18:18
Sorry for late response @PureIncompetence.

Instead of having a default zoom preference, would "remembering" the last zoom level of a connection solve this issue? This provides a more generic solution, without any effort from user's side. And users don't have to think about which particular zoom value will fill the screen.


@user8446, IMO, Remembering the zoom level also removes the need to allow Minimum Zoom above 100%, as we were discussing in #66.

**Comment by user8446** [comment] 2022-07-18 20:55
Great idea... remembering the last zoom level would solve both issues

**Comment by gujjwal00** [comment] 2022-07-28 15:15
I don't mind adding a preference, but I beleive in this case remembering last level is more simple and effective. Single preference might not fit servers with different resolution/aspect-ratio. It also forces us to link different zoom levels (min, max, defaults) together so they can't be set to contradictory values. 


I mainly worry about the Input Settings. For AVNC, I have worked hardest on input handling (followed by layout issues like zooming and panning), and I am kind of proud of what AVNC can do in this area. I mean simplicity in terms of being able to easily grasp & navigate, not in terms of pref count, although having fewer prefs does help. So I like to have fewer prefs, but not at the cost of user personalization. Furthermore, this is just a goal, not something set in stone. Its not like users fiddle with settings everyday 😀.

Yes, it would be per-orientation, but I am thinking of having a **'Separate zoom level for each orientation'** preference to allow current behavior of single zoom level.

**Comment by gujjwal00** [comment] 2022-08-04 12:34
> Regarding the 90%-limit: If possible it imho would make sense to base that height on either (in fullscreen mode) the complete availible display height or (if navbar + notification bar are shown) on the availible space between them.

It already works like that.

> Your proposal (to save / restore the latest zoom level) does sound promising nonetheless, as would certainly solve more use cases than my approach, which only focusses on the portrait mode zoom level

Yes, but now we don't have to remember it per-orientation. Because base scale is different for each orientation, single zoom level works optimally in both orientations, and it really simplifies the implementation.
 
And just a thought, but if optimizing for portrait mode solves the issue, is remembering zoom level really required anymore? Because I believe @user8446 was having the same issue as yours where initial zoom level was insufficient.

**Comment by gujjwal00** [comment] 2022-10-19 16:43
I have thought a lot about this issue, and tried multiple solutions, but none of them seemed to properly satisfy everyone (including me).
- Remembering previous zoom backfires sometimes. If I was zoomed-in on something before closing the session, next time the zoom is too big or too small, and I have to immediately adjust it.
- Automatically increasing the frame size in portrait mode is also problematic. Even if using 90% height, the frame is slightly pixelated/blurry. And only about 20% of remote screen is visible for me (phone is 2400x1080, remote is 1920x1080), which means I have to zoom-out or constantly pan around.
- Having a single global default zoom is unlikely to be fit for different servers with different resolutions.
- I tried having having a default zoom field in advanced server options, but the user experience is not optimal because it usually takes multiple attempts to find the correct default. It also turned out to be surprisingly complex to handle per-orientation default zoom with this approach.

##
But I think my latest attempt will solve all issues:
1. Extend the toolbar drawer to provide an option to save current zoom. 'Reset zoom' button will be replaced by a 'Zoom options' button. When clicked, it will show additional options to reset and save zoom. 'Reset zoom' will work as before and set zoom level to 100%. 'Save zoom' will save current zoom to this server, and it will be used as default for this server.   

    ![screenshot3](https://user-images.githubusercontent.com/27951674/196707589-e8043ed5-5a64-4dae-a053-33b5fea3fc6a.jpg)
    
2. Add an option named `Separate zoom for each orientation` to 'Settings => Viewer => Zoom'. When enabled, AVNC will use separate zoom levels for each orientation, and zooming in one orientation won't affect zoom level in other orientation. Currently, enabling it will also cause the frame to be automatically enlarged to about 80% of the height, but I am on the edge about this particular behavior.
3. Just as a convenience, and to somewhat mimic the old functionality, long-pressing the 'Zoom options' button will also reset the zoom. 

Test APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/9822265/app-debug.zip)

There are still some polishing needed (like providing feedback when saving zoom level), but please test it out and let me know if you have any feedback.

**Comment by user8446** [comment] 2022-10-21 18:45
@gujjwal00 I've been testing, nice work here!!

I think the zoom save feature is spot on! Each user can save their own default in each orientation. Easy.

As for the 80% default height when on, my opinion is I don't think it's needed, who knows what each user wants. I think just a simple toggle to either save or not save would do the trick to make it simple for the users.

**Comment by gujjwal00** [comment] 2022-10-22 08:02
Thanks for testing!

> As for the 80% default height when on, my opinion is I don't think it's needed, who knows what each user wants.

Yeah, I agree. Because setting default zoom is so trivial now, I don't think we need to be extra clever here.

> I think just a simple toggle to either save or not save would do the trick to make it simple for the users.

Can you please explain a bit more here? Are you talking about another option in Settings?

**Comment by user8446** [comment] 2022-10-22 23:38
> Can you please explain a bit more here? Are you talking about another option in Settings?

Thinking about this more, `Separate zoom for each orientation` would probably be best in the toolbar drawer zoom options to group zoom settings together.

Also I'm not sure if it was intended or not but toggling `Separate zoom for each orientation` off turns off the ability to save altogether.

**Comment by gujjwal00** [comment] 2022-10-23 01:25
> Thinking about this more, Separate zoom for each orientation would probably be best in the toolbar drawer zoom options to group zoom settings together.

The reason here is that `Separate zoom for each orientation` works globally, and is not specific to a particular server. So it resides with other global zoom settings like min/max. 'Save zoom' on the other hand is per-server, it only changes default zoom for currently connected server. Both of these features work independently of each other.

> Also I'm not sure if it was intended or not but toggling Separate zoom for each orientation off turns off the ability to save altogether.

I am not able to reproduce this. I can save the zoom irrespective of whether `Separate zoom for each orientation` is on/off. One thing to note here is that 'Save zoom' is available only for saved servers. It won't be available for connections started using top urlbar or discovered servers.

**Comment by user8446** [comment] 2022-10-23 18:32
I tested again and it does work exactly how you described. Thank you for the explanation!

**Comment by user8446** [comment] 2022-10-26 23:47
Looking forward to it, thank you!

**Closed** 2022-11-10 11:00 UTC
