### ISSUE TITLE
[Feature]: the keyboard should popup if the app comes to foreground from background if it was open in the last foreground state.

### ISSUE THREAD

**Issue by Anonymous2716** [gujjwal00/avnc#139] opened 2023-02-12 22:12 UTC
For example , if I was writing something on the vnc screen the  soft keyboard is up. And if I switch apps the keyboard should collapse . and if I come back it should come up again. And if it was not up it shouldn't come up.

Also I've noticed as of writing this issue , the current version broke the extra keys positioning. It should have been right on top of the soft keyboard when opened but instead it goes right behind the soft keyboard on the bottom of the screen. Therefore every time I have to press any key  I have to collapse the keyboard press and bring the keyboard up with the sliding options.

**Comment by nahuhh** [comment] 2023-02-21 18:54
I think: option to open keyboard automatically  portrait/landscape/always/off is good. 
Still should be able to minimize the keyboard manually like you can currently.

personally i always keep the keyboard open when browsing in portrait

**Comment by gujjwal00** [comment] 2023-02-28 08:40
Partially fixed via https://github.com/gujjwal00/avnc/commit/2b17828cd3045887e6b100f628d8a6f6033438ca
Test APK: https://github.com/gujjwal00/avnc/suites/11246069184/artifacts/576019827

Keyboard should now be restored when AVNC comes back to foreground on Android 12+ devices. Unfortunately, I could not find a suitable way to implement this on prior versions.

> Also I've noticed as of writing this issue , the current version broke the extra keys positioning. It should have been right on top of the soft keyboard when opened but instead it goes right behind the soft keyboard on the bottom of the screen. Therefore every time I have to press any key I have to collapse the keyboard press and bring the keyboard up with the sliding options.

Please provide some info about your device, like model & vendor, Android version, AVNC version.
And if possible, a screen-recording of the issue will be very helpful.

**Comment by Anonymous2716** [comment] 2023-02-28 08:44
> Please provide some info about your device, like model & vendor, Android version, AVNC version. And if possible, a screen-recording of the issue will be very helpful. 

Sure give me some time.

**Comment by Anonymous2716** [comment] 2023-02-28 09:02
The test apk somewhat fixes the issue.

**Comment by gujjwal00** [comment] 2023-02-28 09:31
Thanks for the video @Anonymous2716 

>  The manufacturer is from.my country not International therefore not saying.

Does you screen has display-cutout, rounded corner, or anything like that?

**Comment by Anonymous2716** [comment] 2023-02-28 10:20
@gujjwal00 welcome. 

Yes top-middle display cutout for the front camera. And display res is 1600x720.

**Comment by gujjwal00** [comment] 2023-02-28 10:25
I have tried a few different devices, but I can't reproduce the issue.
Can you try disabling **Settings => Viewer => Fullscreen**?

> The test apk somewhat fixes the issue.

Are you talking about keyboard or extra keys?

**Comment by gujjwal00** [comment] 2023-02-28 10:30
Looks like you already disabled fullscreen?

**Comment by Anonymous2716** [comment] 2023-02-28 10:30
> I have tried a few different devices, but I can't reproduce the issue.
Can you try disabling Settings => Viewer => Fullscreen?

I will try. And in which app? The test app or from fdroid/github-release?

> Are you talking about keyboard or extra keys?

Extra keys.

**Comment by gujjwal00** [comment] 2023-02-28 10:40
> The test app or from fdroid/github-release?

You can try both.

When you said the issue is somewhat fixed, what do you mean by "somewhat"?

**Comment by Anonymous2716** [comment] 2023-02-28 10:40
Here is my typical settings:

![Screenshot_20230228-163905](https://user-images.githubusercontent.com/78570872/221830192-5639dbb5-70a4-42ab-ad83-7145c36364c1.png)

![Screenshot_20230228-163920](https://user-images.githubusercontent.com/78570872/221830234-bcf1ee2c-1cf2-4d91-a209-17f613f5f78a.png)

![Screenshot_20230228-163916](https://user-images.githubusercontent.com/78570872/221830215-0596f6dd-6ce2-4507-9caa-e726ec0c7d69.png)

**Comment by gujjwal00** [comment] 2023-02-28 10:43
Please try disabling `Draw behind display cutout`.

**Comment by Anonymous2716** [comment] 2023-02-28 10:46
@gujjwal00 maybe I found the cause. If I disable full screen the extra-keys goes behind the keyboard. And with full screen it stays on top of the keyboard. (Test app)

**Comment by Anonymous2716** [comment] 2023-02-28 10:49
Confirmed on both app  (test, fdroid). and `Draw behind display cutout` doesn't affect anything.

**Comment by nahuhh** [comment] 2023-02-28 13:30
To get back to the main issue
>And if I switch apps the keyboard should collapse . and if I come back it should come up again. And if it was not up it shouldn't come up.

>Keyboard should now be restored when AVNC comes back to foreground on Android 12+ devices. Unfortunately, I could not find a suitable way to implement this on prior versions.

Im running android 10, so the test apk seems to not make any difference, as expected. I assume the OP still have the same behavior as well, considering android 9.

Perhaps a setting for "open keyboard automatically <remember|always|never>" 

- remember = (android 12+ only?) - Perhaps a workaround for older os could be similar to the custom zoom setting. 
1. _automatically_ save the keyboard state on each change (whereas zoom saves manually)
2. restore the setting when
i. brought to foreground after a background event (android 12 only?)
ii. connecting or reconnecting (all os)

- always = open kb when  
i. brought to foreground after a background event (android 12 only?)
ii. connecting or reconnecting (all os) (allow manually closing)

- never = old behavior. Manually open kb

**Comment by Anonymous2716** [comment] 2023-02-28 13:34
> Im running android 10, so the test apk seems to not make any difference, as expected. I assume the OP still have the same behavior as well, considering android 9.

Yep.

**Comment by gujjwal00** [comment] 2023-02-28 14:06
>automatically save the keyboard state on each change (whereas zoom saves manually)
restore the setting when

This is precisely what I tried to do. I ran into two major issues:
- There is no official API to check if keyboard is visible on versions earlier than Android 10.
- So I tried to support at-least 10+, but by the time VncActivity is stopped, the API reports that keyboard is not visible.

So even if I could find some hack to detect keyboard visibility, I can't use it save the state across activity lifecycle.

**Comment by gujjwal00** [comment] 2023-02-28 16:07
@Anonymous2716 please test the following APK:  [app-debug.zip](https://github.com/gujjwal00/avnc/files/10852179/app-debug.zip). 
This should layout extra keys correctly.

**Comment by Anonymous2716** [comment] 2023-02-28 19:05
@gujjwal00 seems to be fixed now. But I got a question. Are the supposed to stay open even after I click swipe>keyboard or extra keys button after opening keyboard/E.K.?

**Comment by gujjwal00** [comment] 2023-03-01 04:02
>  Are the supposed to stay open even after I click swipe>keyboard or extra keys button after opening keyboard/E.K.?

If you opened extra keys manually (swipe & tap on middle button), it will remain open until you manually close it.
If opened automatically with keyboard, it will close automatically with keyboard.

**Comment by Anonymous2716** [comment] 2023-03-01 04:07
@gujjwal00 oh I got it thanks.

**Comment by gujjwal00** [comment] 2023-03-13 12:23
v2.2.0 is now available.

**Closed by gujjwal00** 2023-03-13 12:23 UTC

**Comment by Anonymous2716** [comment] 2023-03-13 12:32
@gujjwal00 just curious will there be keyboard  popup /collapse support below android 12?

**Comment by Anonymous2716** [comment] 2023-03-13 22:21
@gujjwal00 on the latest version 2.2.0 the clipboard sync is not working can you confirm this? I'm using togervnc server version 1.10.1

**Comment by gujjwal00** [comment] 2023-03-14 00:26
It should work correctly. I have tested with TigerVNC 1.12, vino, TightVNC. Does tigervnc logs indicate something?

**Comment by Anonymous2716** [comment] 2023-03-14 08:17
@gujjwal00  not really. Only error I for in the log is `Xlib:  extension "DPMS" missing on display ":1.0".`

**Comment by gujjwal00** [comment] 2023-03-18 03:16
@Anonymous2716,  I am opening a separate issue for for better tracking.

**Comment by bklaase** [comment] 2023-12-25 08:30
@gujjwal00, Sorry to necropost, but even if intuitive brhavior as proposed is not feasable on older android, perhaps could an "keep keyboard active" be a solution?
